/* terminfo.h gets generated from terminfo.def.h and the terminfo database */

#undef ENTRY_BOOLEAN
#undef ENTRY_NUMBER
#undef ENTRY_STRING

#ifdef TERMINFO_ENUM
#ifdef TERMINFO_BOOLEAN
#define ENTRY_BOOLEAN(x,i) TB_ ## x = i,
#endif
#ifdef TERMINFO_NUMBER
#define ENTRY_NUMBER(x,i) TN_ ## x ,
#endif
#ifdef TERMINFO_STRING
#define ENTRY_STRING(x,i) TS_ ## x ,
#endif
#endif
#ifdef TERMINFO_RAW_NAMES
#ifdef TERMINFO_BOOLEAN
#define ENTRY_BOOLEAN(x,i) x
#endif
#ifdef TERMINFO_NUMBER
#define ENTRY_NUMBER(x,i) x
#endif
#ifdef TERMINFO_STRING
#define ENTRY_STRING(x,i) x
#endif
#endif
#ifdef TERMINFO_MAP
#ifdef TERMINFO_NUMBER
#define ENTRY_NUMBER(x,i) i,
#endif
#ifdef TERMINFO_STRING
#define ENTRY_STRING(x,i) i,
#endif
#endif
#ifndef TERMINFO_BOOLEAN
#define ENTRY_BOOLEAN(x,i)
#endif
#ifndef TERMINFO_NUMBER
#define ENTRY_NUMBER(x,i)
#endif
#ifndef TERMINFO_STRING
#define ENTRY_STRING(x,i)
#endif

/* supported terminal extensions */
/* taken from ncurses' term.h */

#ifdef TERMINFO_BOOLEAN
#ifdef TERMINFO_ENUM
typedef enum {
#endif
ENTRY_BOOLEAN(AUTO_LEFT_MARGIN, 0)
ENTRY_BOOLEAN(AUTO_RIGHT_MARGIN, 1)
ENTRY_BOOLEAN(NO_ESC_CTLC, 2)
ENTRY_BOOLEAN(CEOL_STANDOUT_GLITCH, 3)
ENTRY_BOOLEAN(EAT_NEWLINE_GLITCH, 4)
ENTRY_BOOLEAN(ERASE_OVERSTRIKE, 5)
ENTRY_BOOLEAN(GENERIC_TYPE, 6)
ENTRY_BOOLEAN(HARD_COPY, 7)
ENTRY_BOOLEAN(HAS_META_KEY, 8)
ENTRY_BOOLEAN(HAS_STATUS_LINE, 9)
ENTRY_BOOLEAN(INSERT_NULL_GLITCH, 10)
ENTRY_BOOLEAN(MEMORY_ABOVE, 11)
ENTRY_BOOLEAN(MEMORY_BELOW, 12)
ENTRY_BOOLEAN(MOVE_INSERT_MODE, 13)
ENTRY_BOOLEAN(MOVE_STANDOUT_MODE, 14)
ENTRY_BOOLEAN(OVER_STRIKE, 15)
ENTRY_BOOLEAN(STATUS_LINE_ESC_OK, 16)
ENTRY_BOOLEAN(DEST_TABS_MAGIC_SMSO, 17)
ENTRY_BOOLEAN(TILDE_GLITCH, 18)
ENTRY_BOOLEAN(TRANSPARENT_UNDERLINE, 19)
ENTRY_BOOLEAN(XON_XOFF, 20)
ENTRY_BOOLEAN(NEEDS_XON_XOFF, 21)
ENTRY_BOOLEAN(PRTR_SILENT, 22)
ENTRY_BOOLEAN(HARD_CURSOR, 23)
ENTRY_BOOLEAN(NON_REV_RMCUP, 24)
ENTRY_BOOLEAN(NO_PAD_CHAR, 25)
ENTRY_BOOLEAN(NON_DEST_SCROLL_REGION, 26)
ENTRY_BOOLEAN(CAN_CHANGE, 27)
ENTRY_BOOLEAN(BACK_COLOR_ERASE, 28)
ENTRY_BOOLEAN(HUE_LIGHTNESS_SATURATION, 29)
ENTRY_BOOLEAN(COL_ADDR_GLITCH, 30)
ENTRY_BOOLEAN(CR_CANCELS_MICRO_MODE, 31)
ENTRY_BOOLEAN(HAS_PRINT_WHEEL, 32)
ENTRY_BOOLEAN(ROW_ADDR_GLITCH, 33)
ENTRY_BOOLEAN(SEMI_AUTO_RIGHT_MARGIN, 34)
ENTRY_BOOLEAN(CPI_CHANGES_RES, 35)
ENTRY_BOOLEAN(LPI_CHANGES_RES, 36)
#ifdef TERMINFO_ENUM
} terminfo_boolean;
#endif
#endif

#ifdef TERMINFO_STRING
#ifdef TERMINFO_ENUM
typedef enum {
#endif
#ifdef TERMINFO_MAP
static int terminfo_map_string[] = {
#endif
#endif

/* functions */
ENTRY_STRING(CLEAR_SCREEN        ,5 )
ENTRY_STRING(CURSOR_INVISIBLE    ,13)
ENTRY_STRING(CURSOR_NORMAL       ,16)
ENTRY_STRING(ENTER_BLINK_MODE    ,26)
ENTRY_STRING(ENTER_BOLD_MODE     ,27)
ENTRY_STRING(ENTER_CA_MODE       ,28)
ENTRY_STRING(ENTER_REVERSE_MODE  ,34)
ENTRY_STRING(ENTER_UNDERLINE_MODE,36)
ENTRY_STRING(EXIT_ATTRIBUTE_MODE ,39)
ENTRY_STRING(EXIT_CA_MODE        ,40)
ENTRY_STRING(KEYPAD_LOCAL        ,88)
ENTRY_STRING(KEYPAD_XMIT         ,89)
/* keys */
ENTRY_STRING(KEY_F1              ,66)
ENTRY_STRING(KEY_F2              ,68)
ENTRY_STRING(KEY_F3              ,69)
ENTRY_STRING(KEY_F4              ,70)
ENTRY_STRING(KEY_F5              ,71)
ENTRY_STRING(KEY_F6              ,72)
ENTRY_STRING(KEY_F7              ,73)
ENTRY_STRING(KEY_F8              ,74)
ENTRY_STRING(KEY_F9              ,75)
ENTRY_STRING(KEY_F10             ,67)
ENTRY_STRING(KEY_F11             ,216)
ENTRY_STRING(KEY_F12             ,217)
ENTRY_STRING(KEY_IC              ,77)
ENTRY_STRING(KEY_DC              ,58)
ENTRY_STRING(KEY_HOME            ,76)
ENTRY_STRING(KEY_END             ,164)
ENTRY_STRING(KEY_PPAGE           ,82)
ENTRY_STRING(KEY_NPAGE           ,81)
ENTRY_STRING(KEY_UP              ,87)
ENTRY_STRING(KEY_DOWN            ,61)
ENTRY_STRING(KEY_LEFT            ,79)
ENTRY_STRING(KEY_RIGHT           ,83)

#ifdef TERMINFO_STRING
#ifdef TERMINFO_ENUM
TI_MAX
#endif
#ifdef TERMINFO_ENUM
} terminfo_string;
#endif
#ifdef TERMINFO_MAP
};
#endif
#endif
